# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleorder',
            name='store',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orderbot.TeleStore'),
        ),
    ]
