# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbot', '0002_auto_20171122_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telebalancehistory',
            name='category',
            field=models.CharField(choices=[('create_orderitem', 'create order item'), ('delete_orderitem', 'delete order item'), ('cancel_order', 'cancel order'), ('discard_order', 'discard order'), ('recharge', 'recharge'), ('transfer', 'transfer')], max_length=20),
        ),
    ]
