# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbot', '0003_auto_20180118_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleuser',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
